[package]
name = "sep"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
license-file = "../LICENSE"

[dependencies]
config-deserializer = { path = "../config-deserializer" }
parser = { path = "../parser" }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
